import streamlit as st
import joblib
import pandas as pd
import numpy as np

# Load the trained pipeline
try:
    full_pipeline = joblib.load('full_pipeline.pkl')
except FileNotFoundError:
    st.error("Pipeline file not found. Make sure 'full_pipeline.pkl' is in the same directory.")
    st.stop()

# --- Website Title and Description ---
st.title("Crop Production and Yield Prediction")
st.markdown("""
Welcome to the Crop Production and Yield Prediction App!
Input the details below to get predictions for crop production and yield.
""")

# --- Input Fields ---
st.header("Input Features")

# Get unique values for dropdowns from the original dataset (X_mod)
# Assuming X_mod is available in the environment or loaded from a file
# If X_mod is not available, you would need to load it or get the unique values
# from the original data source. For this example, we'll assume X_mod is a DataFrame.

# You might need to load X_mod here if it's not available in the current environment
# X_mod = pd.read_csv("/content/India Agriculture Crop Production(1).csv") # Adjust path if necessary
# You would also need to apply the same data cleaning steps as in the notebook
# to X_mod before extracting unique values.

# For demonstration purposes, let's use some sample data for dropdowns
# In a real application, load and clean the original data to get these values
try:
    # Assuming X_mod is available in the environment from the previous steps
    states = ['Andaman and Nicobar Islands',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Dadra and Nagar Haveli',
 'Daman and Diu',
 'Delhi',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu and Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Telangana',
 'Tripura',
 'Uttar Pradesh',
 'Uttarakhand',
 'West Bengal']
    districts = ['24 PARAGANAS NORTH',
 '24 PARAGANAS SOUTH',
 'ADILABAD',
 'AGAR MALWA',
 'AGRA',
 'AHMADABAD',
 'AHMEDNAGAR',
 'AIZAWL',
 'AJMER',
 'AKOLA',
 'ALAPPUZHA',
 'ALIGARH',
 'ALIPURDUAR',
 'ALIRAJPUR',
 'ALLAHABAD',
 'ALMORA',
 'ALWAR',
 'AMBALA',
 'AMBEDKAR NAGAR',
 'AMETHI',
 'AMRAVATI',
 'AMRELI',
 'AMRITSAR',
 'AMROHA',
 'ANAND',
 'ANANTAPUR',
 'ANANTNAG',
 'ANJAW',
 'ANUGUL',
 'ANUPPUR',
 'ARARIA',
 'ARAVALLI',
 'ARIYALUR',
 'ARWAL',
 'ASHOKNAGAR',
 'AURAIYA',
 'AURANGABAD',
 'AZAMGARH',
 'Andaman and Nicobar Islands',
 'BADGAM',
 'BAGALKOT',
 'BAGALKOTE',
 'BAGESHWAR',
 'BAGHPAT',
 'BAHRAICH',
 'BAKSA',
 'BALAGHAT',
 'BALANGIR',
 'BALESHWAR',
 'BALLARI',
 'BALLIA',
 'BALOD',
 'BALODA BAZAR',
 'BALRAMPUR',
 'BANAS KANTHA',
 'BANDA',
 'BANDIPORA',
 'BANGALORE RURAL',
 'BANKA',
 'BANKURA',
 'BANSWARA',
 'BARABANKI',
 'BARAMULLA',
 'BARAN',
 'BAREILLY',
 'BARGARH',
 'BARMER',
 'BARNALA',
 'BARPETA',
 'BARWANI',
 'BASTAR',
 'BASTI',
 'BATHINDA',
 'BEED',
 'BEGUSARAI',
 'BELAGAVI',
 'BELGAUM',
 'BELLARY',
 'BEMETARA',
 'BENGALURU URBAN',
 'BETUL',
 'BHADRADRI',
 'BHADRAK',
 'BHAGALPUR',
 'BHANDARA',
 'BHARATPUR',
 'BHARUCH',
 'BHAVNAGAR',
 'BHILWARA',
 'BHIND',
 'BHIWANI',
 'BHOJPUR',
 'BHOPAL',
 'BIDAR',
 'BIJAPUR',
 'BIJNOR',
 'BIKANER',
 'BILASPUR',
 'BIRBHUM',
 'BISHNUPUR',
 'BISWANATH',
 'BOKARO',
 'BONGAIGAON',
 'BOTAD',
 'BOUDH',
 'BUDAUN',
 'BULANDSHAHR',
 'BULDHANA',
 'BUNDI',
 'BURHANPUR',
 'BUXAR',
 'CACHAR',
 'CHAMARAJANAGAR',
 'CHAMARAJANAGARA',
 'CHAMBA',
 'CHAMOLI',
 'CHAMPAWAT',
 'CHAMPHAI',
 'CHANDAULI',
 'CHANDEL',
 'CHANDIGARH',
 'CHANDRAPUR',
 'CHANGLANG',
 'CHARAIDEO',
 'CHARKI DADRI',
 'CHATRA',
 'CHENGALPATTU',
 'CHENNAI',
 'CHHATARPUR',
 'CHHINDWARA',
 'CHHOTAUDEPUR',
 'CHIKBALLAPUR',
 'CHIKKABALLAPURA',
 'CHIKKAMAGALURU',
 'CHIKMAGALUR',
 'CHIRANG',
 'CHITRADURGA',
 'CHITRAKOOT',
 'CHITTOOR',
 'CHITTORGARH',
 'CHURACHANDPUR',
 'CHURU',
 'COIMBATORE',
 'COOCHBEHAR',
 'CUDDALORE',
 'CUTTACK',
 'DADRA AND NAGAR HAVELI',
 'DAKSHIN KANNAD',
 'DAKSHINA KANNADA',
 'DAMAN',
 'DAMOH',
 'DANG',
 'DANTEWADA',
 'DARBHANGA',
 'DARJEELING',
 'DARRANG',
 'DATIA',
 'DAUSA',
 'DAVANGERE',
 'DEHRADUN',
 'DELHI_TOTAL',
 'DEOGARH',
 'DEOGHAR',
 'DEORIA',
 'DEVBHUMI DWARKA',
 'DEWAS',
 'DHALAI',
 'DHAMTARI',
 'DHANBAD',
 'DHAR',
 'DHARMAPURI',
 'DHARWAD',
 'DHEMAJI',
 'DHENKANAL',
 'DHOLPUR',
 'DHUBRI',
 'DHULE',
 'DIBANG VALLEY',
 'DIBRUGARH',
 'DIMA HASAO',
 'DIMAPUR',
 'DINAJPUR DAKSHIN',
 'DINAJPUR UTTAR',
 'DINDIGUL',
 'DINDORI',
 'DIU',
 'DODA',
 'DOHAD',
 'DUMKA',
 'DUNGARPUR',
 'DURG',
 'Daman and Diu',
 'Delhi',
 'EAST DISTRICT',
 'EAST GARO HILLS',
 'EAST GODAVARI',
 'EAST JAINTIA HILLS',
 'EAST KAMENG',
 'EAST KHASI HILLS',
 'EAST SIANG',
 'EAST SINGHBUM',
 'ERNAKULAM',
 'ERODE',
 'ETAH',
 'ETAWAH',
 'FAIZABAD',
 'FARIDABAD',
 'FARIDKOT',
 'FARRUKHABAD',
 'FATEHABAD',
 'FATEHGARH SAHIB',
 'FATEHPUR',
 'FAZILKA',
 'FIROZABAD',
 'FIROZEPUR',
 'GADAG',
 'GADCHIROLI',
 'GAJAPATI',
 'GANDERBAL',
 'GANDHINAGAR',
 'GANGANAGAR',
 'GANJAM',
 'GARHWA',
 'GARIYABAND',
 'GAURELLA-PENDRA-MARWAHI',
 'GAUTAM BUDDHA NAGAR',
 'GAYA',
 'GHAZIABAD',
 'GHAZIPUR',
 'GIR SOMNATH',
 'GIRIDIH',
 'GOALPARA',
 'GODDA',
 'GOLAGHAT',
 'GOMATI',
 'GONDA',
 'GONDIA',
 'GOPALGANJ',
 'GORAKHPUR',
 'GULBARGA',
 'GUMLA',
 'GUNA',
 'GUNTUR',
 'GURDASPUR',
 'GURGAON',
 'GWALIOR',
 'Goa',
 'HAILAKANDI',
 'HAMIRPUR',
 'HANUMAKONDA',
 'HANUMANGARH',
 'HAPUR',
 'HARDA',
 'HARDOI',
 'HARIDWAR',
 'HASSAN',
 'HATHRAS',
 'HAVERI',
 'HAZARIBAGH',
 'HINGOLI',
 'HISAR',
 'HOJAI',
 'HOOGHLY',
 'HOSHANGABAD',
 'HOSHIARPUR',
 'HOWRAH',
 'HYDERABAD',
 'IDUKKI',
 'IMPHAL EAST',
 'IMPHAL WEST',
 'INDORE',
 'JABALPUR',
 'JAGATSINGHAPUR',
 'JAGITIAL',
 'JAIPUR',
 'JAISALMER',
 'JAJAPUR',
 'JALANDHAR',
 'JALAUN',
 'JALGAON',
 'JALNA',
 'JALORE',
 'JALPAIGURI',
 'JAMMU',
 'JAMNAGAR',
 'JAMTARA',
 'JAMUI',
 'JANGOAN',
 'JANJGIR-CHAMPA',
 'JASHPUR',
 'JAUNPUR',
 'JAYASHANKAR',
 'JEHANABAD',
 'JHABUA',
 'JHAJJAR',
 'JHALAWAR',
 'JHANSI',
 'JHARGRAM',
 'JHARSUGUDA',
 'JHUNJHUNU',
 'JIND',
 'JODHPUR',
 'JOGULAMBA',
 'JORHAT',
 'JUNAGADH',
 'KABIRDHAM',
 'KACHCHH',
 'KADAPA',
 'KAIMUR (BHABUA)',
 'KAITHAL',
 'KALABURAGI',
 'KALAHANDI',
 'KALIMPONG',
 'KALLAKURICHI',
 'KAMAREDDY',
 'KAMLE',
 'KAMRUP',
 'KAMRUP METRO',
 'KANCHIPURAM',
 'KANDHAMAL',
 'KANGRA',
 'KANKER',
 'KANNAUJ',
 'KANNIYAKUMARI',
 'KANNUR',
 'KANPUR DEHAT',
 'KANPUR NAGAR',
 'KAPURTHALA',
 'KARAIKAL',
 'KARAULI',
 'KARBI ANGLONG',
 'KARGIL',
 'KARIMGANJ',
 'KARIMNAGAR',
 'KARNAL',
 'KARUR',
 'KASARAGOD',
 'KASGANJ',
 'KATHUA',
 'KATIHAR',
 'KATNI',
 'KAUSHAMBI',
 'KENDRAPARA',
 'KENDUJHAR',
 'KHAGARIA',
 'KHAMMAM',
 'KHANDWA',
 'KHARGONE',
 'KHEDA',
 'KHERI',
 'KHORDHA',
 'KHOWAI',
 'KHUNTI',
 'KINNAUR',
 'KIPHIRE',
 'KISHANGANJ',
 'KISHTWAR',
 'KODAGU',
 'KODERMA',
 'KOHIMA',
 'KOKRAJHAR',
 'KOLAR',
 'KOLASIB',
 'KOLHAPUR',
 'KOLLAM',
 'KOMARAM BHEEM ASIFABAD',
 'KONDAGAON',
 'KOPPAL',
 'KORAPUT',
 'KORBA',
 'KOREA',
 'KOTA',
 'KOTTAYAM',
 'KOZHIKODE',
 'KRA DAADI',
 'KRISHNA',
 'KRISHNAGIRI',
 'KULGAM',
 'KULLU',
 'KUPWARA',
 'KURNOOL',
 'KURUKSHETRA',
 'KURUNG KUMEY',
 'KUSHI NAGAR',
 'LAHUL AND SPITI',
 'LAKHIMPUR',
 'LAKHISARAI',
 'LALITPUR',
 'LATEHAR',
 'LATUR',
 'LAWNGTLAI',
 'LEH LADAKH',
 'LEPARADA',
 'LOHARDAGA',
 'LOHIT',
 'LONGDING',
 'LONGLENG',
 'LOWER DIBANG VALLEY',
 'LOWER SIANG',
 'LOWER SUBANSIRI',
 'LUCKNOW',
 'LUDHIANA',
 'LUNGLEI',
 'MADHEPURA',
 'MADHUBANI',
 'MADURAI',
 'MAHABUBABAD',
 'MAHARAJGANJ',
 'MAHASAMUND',
 'MAHBUBNAGAR',
 'MAHE',
 'MAHENDRAGARH',
 'MAHESANA',
 'MAHISAGAR',
 'MAHOBA',
 'MAINPURI',
 'MAJULI',
 'MALAPPURAM',
 'MALDAH',
 'MALKANGIRI',
 'MAMIT',
 'MANCHERIAL',
 'MANDI',
 'MANDLA',
 'MANDSAUR',
 'MANDYA',
 'MANSA',
 'MARIGAON',
 'MATHURA',
 'MAU',
 'MAYURBHANJ',
 'MEDAK',
 'MEDCHAL',
 'MEDCHAL MALKAJGIRI',
 'MEDINIPUR EAST',
 'MEDINIPUR WEST',
 'MEERUT',
 'MEWAT',
 'MIRZAPUR',
 'MOGA',
 'MOKOKCHUNG',
 'MON',
 'MORADABAD',
 'MORBI',
 'MORENA',
 'MUKTSAR',
 'MULUGU',
 'MUMBAI',
 'MUMBAI SUBURBAN',
 'MUNGELI',
 'MUNGER',
 'MURSHIDABAD',
 'MUZAFFARNAGAR',
 'MUZAFFARPUR',
 'MYSORE',
 'MYSURU',
 'NABARANGPUR',
 'NADIA',
 'NAGAON',
 'NAGAPATTINAM',
 'NAGARKURNOOL',
 'NAGAUR',
 'NAGPUR',
 'NAINITAL',
 'NALANDA',
 'NALBARI',
 'NALGONDA',
 'NAMAKKAL',
 'NAMSAI',
 'NANDED',
 'NANDURBAR',
 'NARAYANAPET',
 'NARAYANPUR',
 'NARMADA',
 'NARSINGHPUR',
 'NASHIK',
 'NAVSARI',
 'NAWADA',
 'NAWANSHAHR',
 'NAYAGARH',
 'NEEMUCH',
 'NICOBARS',
 'NIRMAL',
 'NIWARI',
 'NIZAMABAD',
 'NORTH AND MIDDLE ANDAMAN',
 'NORTH DISTRICT',
 'NORTH GARO HILLS',
 'NORTH GOA',
 'NORTH TRIPURA',
 'NUAPADA',
 'OSMANABAD',
 'PAKKE KESSANG',
 'PAKUR',
 'PALAKKAD',
 'PALAMU',
 'PALGHAR',
 'PALI',
 'PALWAL',
 'PANCH MAHALS',
 'PANCHKULA',
 'PANIPAT',
 'PANNA',
 'PAPUM PARE',
 'PARBHANI',
 'PASCHIM BARDHAMAN',
 'PASHCHIM CHAMPARAN',
 'PATAN',
 'PATHANAMTHITTA',
 'PATHANKOT',
 'PATIALA',
 'PATNA',
 'PAURI GARHWAL',
 'PEDDAPALLI',
 'PERAMBALUR',
 'PEREN',
 'PHEK',
 'PILIBHIT',
 'PITHORAGARH',
 'PONDICHERRY',
 'POONCH',
 'PORBANDAR',
 'PRAKASAM',
 'PRATAPGARH',
 'PUDUKKOTTAI',
 'PULWAMA',
 'PUNE',
 'PURBA BARDHAMAN',
 'PURBI CHAMPARAN',
 'PURI',
 'PURNIA',
 'PURULIA',
 'RAE BARELI',
 'RAICHUR',
 'RAIGAD',
 'RAIGARH',
 'RAIPUR',
 'RAISEN',
 'RAJANNA',
 'RAJAURI',
 'RAJGARH',
 'RAJKOT',
 'RAJNANDGAON',
 'RAJSAMAND',
 'RAMANAGARA',
 'RAMANATHAPURAM',
 'RAMBAN',
 'RAMGARH',
 'RAMPUR',
 'RANCHI',
 'RANGAREDDI',
 'RANIPET',
 'RATLAM',
 'RATNAGIRI',
 'RAYAGADA',
 'REASI',
 'REWA',
 'REWARI',
 'RI BHOI',
 'ROHTAK',
 'ROHTAS',
 'RUDRA PRAYAG',
 'RUPNAGAR',
 'S',
 'SABAR KANTHA',
 'SAGAR',
 'SAHARANPUR',
 'SAHARSA',
 'SAHEBGANJ',
 'SAIHA',
 'SALEM',
 'SAMASTIPUR',
 'SAMBA',
 'SAMBALPUR',
 'SAMBHAL',
 'SANGAREDDY',
 'SANGLI',
 'SANGRUR',
 'SANT KABEER NAGAR',
 'SANT RAVIDAS NAGAR',
 'SARAIKELA KHARSAWAN',
 'SARAN',
 'SATARA',
 'SATNA',
 'SAWAI MADHOPUR',
 'SEHORE',
 'SENAPATI',
 'SEONI',
 'SEPAHIJALA',
 'SERCHHIP',
 'SHAHDOL',
 'SHAHID BHAGAT SINGH NAGAR',
 'SHAHJAHANPUR',
 'SHAJAPUR',
 'SHAMLI',
 'SHEIKHPURA',
 'SHEOHAR',
 'SHEOPUR',
 'SHI YOMI',
 'SHIMLA',
 'SHIMOGA',
 'SHIVAMOGGA',
 'SHIVPURI',
 'SHOPIAN',
 'SHRAVASTI',
 'SIANG',
 'SIDDHARTH NAGAR',
 'SIDDIPET',
 'SIDHI',
 'SIKAR',
 'SIMDEGA',
 'SINDHUDURG',
 'SINGRAULI',
 'SIRMAUR',
 'SIROHI',
 'SIRSA',
 'SITAMARHI',
 'SITAPUR',
 'SIVAGANGA',
 'SIVASAGAR',
 'SIWAN',
 'SOLAN',
 'SOLAPUR',
 'SONBHADRA',
 'SONEPUR',
 'SONIPAT',
 'SONITPUR',
 'SOUTH ANDAMANS',
 'SOUTH DISTRICT',
 'SOUTH GARO HILLS',
 'SOUTH GOA',
 'SOUTH SALMARA MANCACHAR',
 'SOUTH TRIPURA',
 'SOUTH WEST GARO HILLS',
 'SOUTH WEST KHASI HILLS',
 'SPSR NELLORE',
 'SRIKAKULAM',
 'SRINAGAR',
 'SUKMA',
 'SULTANPUR',
 'SUNDARGARH',
 'SUPAUL',
 'SURAJPUR',
 'SURAT',
 'SURENDRANAGAR',
 'SURGUJA',
 'SURYAPET',
 'TAMENGLONG',
 'TAPI',
 'TARN TARAN',
 'TAWANG',
 'TEHRI GARHWAL',
 'TENKASI',
 'THANE',
 'THANJAVUR',
 'THE NILGIRIS',
 'THENI',
 'THIRUVALLUR',
 'THIRUVANANTHAPURAM',
 'THIRUVARUR',
 'THOOTHUKUDI',
 'THOUBAL',
 'THRISSUR',
 'TIKAMGARH',
 'TINSUKIA',
 'TIRAP',
 'TIRUCHIRAPPALLI',
 'TIRUNELVELI',
 'TIRUPATHUR',
 'TIRUPPUR',
 'TIRUVANNAMALAI',
 'TONK',
 'TUENSANG',
 'TUMAKURU',
 'TUMKUR',
 'TUTICORIN',
 'UDAIPUR',
 'UDALGURI',
 'UDAM SINGH NAGAR',
 'UDHAMPUR',
 'UDUPI',
 'UJJAIN',
 'UKHRUL',
 'UMARIA',
 'UNA',
 'UNAKOTI',
 'UNNAO',
 'UPPER SIANG',
 'UPPER SUBANSIRI',
 'UTTAR KANNAD',
 'UTTAR KASHI',
 'UTTARA KANNADA',
 'VADODARA',
 'VAISHALI',
 'VALSAD',
 'VARANASI',
 'VELLORE',
 'VIDISHA',
 'VIJAYAPURA',
 'VIKARABAD',
 'VILLUPURAM',
 'VIRUDHUNAGAR',
 'VISAKHAPATANAM',
 'VIZIANAGARAM',
 'WANAPARTHY',
 'WARANGAL',
 'WARANGAL URBAN',
 'WARDHA',
 'WASHIM',
 'WAYANAD',
 'WEST DISTRICT',
 'WEST GARO HILLS',
 'WEST GODAVARI',
 'WEST JAINTIA HILLS',
 'WEST KAMENG',
 'WEST KARBI ANGLONG',
 'WEST KHASI HILLS',
 'WEST SIANG',
 'WEST SINGHBHUM',
 'WEST TRIPURA',
 'WOKHA',
 'YADADRI',
 'YADAGIRI',
 'YADGIR',
 'YAMUNANAGAR',
 'YANAM',
 'YAVATMAL',
 'ZUNHEBOTO']
    crops = ['Arecanut',
 'Arhar/Tur',
 'Bajra',
 'Banana',
 'Barley',
 'Black pepper',
 'Cardamom',
 'Cashewnut',
 'Castor seed',
 'Coconut',
 'Coriander',
 'Cotton(lint)',
 'Cowpea(Lobia)',
 'Dry Ginger',
 'Dry chillies',
 'Garlic',
 'Ginger',
 'Gram',
 'Groundnut',
 'Guar seed',
 'Horse-gram',
 'Jowar',
 'Jute',
 'Khesari',
 'Linseed',
 'Maize',
 'Masoor',
 'Mesta',
 'Moong(Green Gram)',
 'Moth',
 'Niger seed',
 'Onion',
 'Peas & beans (Pulses)',
 'Potato',
 'Ragi',
 'Rapeseed &Mustard',
 'Rice',
 'Safflower',
 'Sannhamp',
 'Sesamum',
 'Small millets',
 'Soyabean',
 'Sugarcane',
 'Sunflower',
 'Sweet potato',
 'Tapioca',
 'Tobacco',
 'Turmeric',
 'Urad',
 'Wheat']
    seasons = ['Autumn', 'Kharif', 'Rabi', 'Summer', 'Whole Year', 'Winter']
except NameError:
    st.error("Original data (X_mod) not found. Cannot populate dropdowns. Please ensure X_mod is loaded and processed.")
    st.stop()


state = st.selectbox("State", states)
district = st.selectbox("District", districts)
crop = st.selectbox("Crop", crops)
season = st.selectbox("Season", seasons)
area = st.number_input("Area (in Hectare)", min_value=0.0, format="%f")

# --- Prediction Button ---
if st.button("Predict"):
    # --- Prepare input data for the pipeline ---
    input_data = pd.DataFrame([[state, district, crop, season, area]],
                              columns=['State', 'District', 'Crop', 'Season', 'Area'])

    # --- Make Prediction using the pipeline ---
    # The pipeline handles preprocessing and prediction
    predicted_production = full_pipeline.predict(input_data)[0]

    # --- Calculate Yield ---
    predicted_yield = predicted_production / area if area > 0 else 0

    # --- Display Results ---
    st.header("Prediction Results")
    st.write(f"Predicted Production: {predicted_production:.2f}")
    st.write(f"Predicted Yield (Production/Area): {predicted_yield:.2f}")

